/*
  # Create League Rankings System

  1. Purpose
    - Store imported Sleeper leagues for tracking
    - Generate weekly power rankings based on FDP player values
    - Create public shareable league ranking pages
    - Track historical rankings for trend analysis
    - Drive recurring weekly engagement

  2. New Tables
    
    `leagues`
    - `id` (uuid, primary key) - Unique identifier
    - `sleeper_league_id` (text, unique) - Sleeper league ID
    - `name` (text) - League name
    - `season` (int) - Year (e.g., 2026)
    - `format` (text) - League format (dynasty_1qb, dynasty_sf, etc.)
    - `public_slug` (text, unique) - URL-friendly identifier
    - `is_public` (boolean) - Whether rankings are publicly viewable
    - `owner_user_id` (uuid) - User who imported the league
    - `roster_settings` (jsonb) - Roster configuration
    - `scoring_settings` (jsonb) - Scoring settings
    - `last_sync_at` (timestamptz) - Last time rosters were synced
    - `created_at` (timestamptz) - When imported

    `league_rankings`
    - `id` (uuid, primary key) - Unique identifier
    - `league_id` (uuid) - Foreign key to leagues
    - `week` (int) - NFL week number (0 = preseason/offseason)
    - `roster_id` (int) - Sleeper roster ID
    - `team_name` (text) - Team name
    - `owner_name` (text) - Owner display name
    - `owner_avatar` (text) - Owner avatar URL
    - `offense_value` (int) - Total offensive player value
    - `idp_value` (int) - Total IDP player value (0 if not IDP league)
    - `total_value` (int) - Combined total value
    - `rank` (int) - Rank within league (1 = best)
    - `rank_change` (int) - Change from previous week (null if first week)
    - `player_count` (int) - Number of players on roster
    - `top_player_name` (text) - Highest value player name
    - `top_player_value` (int) - Highest value player value
    - `created_at` (timestamptz) - Snapshot timestamp

  3. Security
    - Enable RLS on both tables
    - Anyone can view public leagues
    - Only league owner can update league settings
    - Rankings are read-only (generated by system)

  4. Indexes
    - Unique index on sleeper_league_id
    - Unique index on public_slug
    - Index on league_rankings (league_id, week) for queries
    - Index on created_at for recent rankings

  5. Helper Functions
    - generate_league_slug() - Create URL-friendly slug
    - get_current_nfl_week() - Calculate current NFL week
*/

-- Create leagues table
CREATE TABLE IF NOT EXISTS leagues (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sleeper_league_id text UNIQUE NOT NULL,
  name text NOT NULL,
  season int NOT NULL,
  format text NOT NULL,
  public_slug text UNIQUE NOT NULL,
  is_public boolean DEFAULT true,
  owner_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  roster_settings jsonb DEFAULT '{}'::jsonb,
  scoring_settings jsonb DEFAULT '{}'::jsonb,
  last_sync_at timestamptz,
  created_at timestamptz DEFAULT now()
);

-- Create league_rankings table
CREATE TABLE IF NOT EXISTS league_rankings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  league_id uuid REFERENCES leagues(id) ON DELETE CASCADE NOT NULL,
  week int NOT NULL,
  roster_id int NOT NULL,
  team_name text NOT NULL,
  owner_name text NOT NULL,
  owner_avatar text,
  offense_value int NOT NULL DEFAULT 0,
  idp_value int NOT NULL DEFAULT 0,
  total_value int NOT NULL DEFAULT 0,
  rank int NOT NULL,
  rank_change int,
  player_count int DEFAULT 0,
  top_player_name text,
  top_player_value int,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE leagues ENABLE ROW LEVEL SECURITY;
ALTER TABLE league_rankings ENABLE ROW LEVEL SECURITY;

-- RLS Policies for leagues

-- Anyone can view public leagues
CREATE POLICY "Anyone can view public leagues"
  ON leagues
  FOR SELECT
  USING (is_public = true);

-- Authenticated users can view their own leagues
CREATE POLICY "Users can view own leagues"
  ON leagues
  FOR SELECT
  TO authenticated
  USING (auth.uid() = owner_user_id);

-- Authenticated users can insert leagues
CREATE POLICY "Authenticated users can create leagues"
  ON leagues
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = owner_user_id);

-- Users can update their own leagues
CREATE POLICY "Users can update own leagues"
  ON leagues
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = owner_user_id)
  WITH CHECK (auth.uid() = owner_user_id);

-- Users can delete their own leagues
CREATE POLICY "Users can delete own leagues"
  ON leagues
  FOR DELETE
  TO authenticated
  USING (auth.uid() = owner_user_id);

-- RLS Policies for league_rankings

-- Anyone can view rankings for public leagues
CREATE POLICY "Anyone can view public league rankings"
  ON league_rankings
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM leagues
      WHERE leagues.id = league_rankings.league_id
      AND leagues.is_public = true
    )
  );

-- Authenticated users can view rankings for their own leagues
CREATE POLICY "Users can view own league rankings"
  ON league_rankings
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM leagues
      WHERE leagues.id = league_rankings.league_id
      AND leagues.owner_user_id = auth.uid()
    )
  );

-- System can insert rankings (service role only)
-- Note: This will be done via Edge Functions with service role key

-- Indexes for performance
CREATE UNIQUE INDEX IF NOT EXISTS idx_leagues_sleeper_id ON leagues(sleeper_league_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_leagues_public_slug ON leagues(public_slug);
CREATE INDEX IF NOT EXISTS idx_leagues_owner ON leagues(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_leagues_public ON leagues(is_public) WHERE is_public = true;

CREATE INDEX IF NOT EXISTS idx_league_rankings_league_week ON league_rankings(league_id, week DESC);
CREATE INDEX IF NOT EXISTS idx_league_rankings_league ON league_rankings(league_id);
CREATE INDEX IF NOT EXISTS idx_league_rankings_created_at ON league_rankings(created_at DESC);

-- Function to generate league slug from name
CREATE OR REPLACE FUNCTION generate_league_slug(league_name text, season_year int)
RETURNS text AS $$
DECLARE
  base_slug text;
  final_slug text;
  counter int := 0;
BEGIN
  -- Convert to lowercase, replace spaces with hyphens, remove special chars
  base_slug := lower(regexp_replace(league_name, '[^a-zA-Z0-9\s-]', '', 'g'));
  base_slug := regexp_replace(base_slug, '\s+', '-', 'g');
  base_slug := regexp_replace(base_slug, '-+', '-', 'g');
  base_slug := trim(both '-' from base_slug);
  
  -- Limit length and add season
  base_slug := substring(base_slug, 1, 40);
  base_slug := base_slug || '-' || season_year::text;
  
  final_slug := base_slug;
  
  -- Check for uniqueness and add counter if needed
  WHILE EXISTS (SELECT 1 FROM leagues WHERE public_slug = final_slug) LOOP
    counter := counter + 1;
    final_slug := base_slug || '-' || counter::text;
  END LOOP;
  
  RETURN final_slug;
END;
$$ LANGUAGE plpgsql VOLATILE;

-- Function to get current NFL week (approximate)
CREATE OR REPLACE FUNCTION get_current_nfl_week()
RETURNS int AS $$
DECLARE
  current_date date := CURRENT_DATE;
  season_start date;
  weeks_elapsed int;
BEGIN
  -- NFL season typically starts first week of September
  -- This is a simplified calculation
  season_start := make_date(EXTRACT(YEAR FROM current_date)::int, 9, 1);
  
  -- If before season start, return 0 (offseason)
  IF current_date < season_start THEN
    RETURN 0;
  END IF;
  
  -- Calculate weeks elapsed
  weeks_elapsed := ((current_date - season_start) / 7)::int + 1;
  
  -- Cap at week 18 (regular season end)
  IF weeks_elapsed > 18 THEN
    RETURN 18;
  END IF;
  
  RETURN weeks_elapsed;
END;
$$ LANGUAGE plpgsql STABLE;

-- Function to get previous week's rankings for a league
CREATE OR REPLACE FUNCTION get_previous_week_rankings(p_league_id uuid, p_current_week int)
RETURNS TABLE (
  roster_id int,
  previous_rank int
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    lr.roster_id,
    lr.rank as previous_rank
  FROM league_rankings lr
  WHERE lr.league_id = p_league_id
  AND lr.week = p_current_week - 1
  AND lr.created_at = (
    SELECT MAX(created_at)
    FROM league_rankings
    WHERE league_id = p_league_id
    AND week = p_current_week - 1
  );
END;
$$ LANGUAGE plpgsql STABLE;

-- View for latest league rankings
CREATE OR REPLACE VIEW latest_league_rankings AS
SELECT DISTINCT ON (lr.league_id, lr.roster_id)
  lr.*,
  l.name as league_name,
  l.public_slug,
  l.is_public,
  l.format
FROM league_rankings lr
JOIN leagues l ON l.id = lr.league_id
ORDER BY lr.league_id, lr.roster_id, lr.week DESC, lr.created_at DESC;

-- Grant permissions
GRANT EXECUTE ON FUNCTION generate_league_slug(text, int) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION get_current_nfl_week() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION get_previous_week_rankings(uuid, int) TO authenticated, anon;
GRANT SELECT ON latest_league_rankings TO authenticated, anon;

-- Add helpful comments
COMMENT ON TABLE leagues IS 
  'Imported Sleeper leagues with public ranking pages';

COMMENT ON TABLE league_rankings IS 
  'Weekly snapshots of team rankings based on FDP player values';

COMMENT ON COLUMN leagues.public_slug IS 
  'URL-friendly identifier for public ranking pages (/league/public/{slug})';

COMMENT ON COLUMN leagues.is_public IS 
  'Privacy toggle - when true, rankings are publicly viewable';

COMMENT ON COLUMN league_rankings.rank_change IS 
  'Change in rank from previous week (positive = improved, negative = declined, null = first week)';

COMMENT ON FUNCTION get_current_nfl_week IS 
  'Returns current NFL week number (0 = offseason, 1-18 = regular season)';
